name: lifebase
version: "1.0.0"
config-version: 2

profile: lifebase

model-paths: ["models"]
macro-paths: ["macros"]

models:
  lifebase:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
